<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fcg.Notifications.Domain\Fcg.Notifications.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Fcg.Notifications.UnitTests" />
  </ItemGroup>

</Project>
